language: elixir
elixir:
  - 1.11
otp_release:
  - 23.0
env:
  MIX_ENV=test

before_script:
  - mix format --check-formatted
  - mix credo --strict --mute-exit-status
  - mix coveralls.travis

script:
  - mix test